/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsExampleRouteImport } from './routes/docs/example'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsInstallRouteImport } from './routes/docs/install'
import { Route as DocsManifestRouteImport } from './routes/docs/manifest'
import { Route as DocsProtocolRouteImport } from './routes/docs/protocol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExampleRoute = DocsExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DocsRoute,
} as any)
const DocsManifestRoute = DocsManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolRoute = DocsProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/docs/example': typeof DocsExampleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manifest': typeof DocsManifestRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/docs/example': typeof DocsExampleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manifest': typeof DocsManifestRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/docs/example': typeof DocsExampleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manifest': typeof DocsManifestRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/privacy'
    | '/docs/example'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/manifest'
    | '/docs/protocol'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/docs/example'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/manifest'
    | '/docs/protocol'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/privacy'
    | '/docs/example'
    | '/docs/faq'
    | '/docs/install'
    | '/docs/manifest'
    | '/docs/protocol'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/example': {
      id: '/docs/example'
      path: '/example'
      fullPath: '/docs/example'
      preLoaderRoute: typeof DocsExampleRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/manifest': {
      id: '/docs/manifest'
      path: '/manifest'
      fullPath: '/docs/manifest'
      preLoaderRoute: typeof DocsManifestRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol': {
      id: '/docs/protocol'
      path: '/protocol'
      fullPath: '/docs/protocol'
      preLoaderRoute: typeof DocsProtocolRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsExampleRoute: typeof DocsExampleRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsManifestRoute: typeof DocsManifestRoute
  DocsProtocolRoute: typeof DocsProtocolRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsExampleRoute: DocsExampleRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsManifestRoute: DocsManifestRoute,
  DocsProtocolRoute: DocsProtocolRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
